; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
;upload_speed = 576000
upload_speed = 315200 
;upload_port = /dev/tty.usbserial-140
monitor_filters = esp32_exception_decoder
board_build.partitions = 8m4m.csv
build_type = debug
lib_deps = 
	mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display@^3.0.10
	fastled/FastLED@^3.6.0
	Wire
	adafruit/Adafruit BusIO
	adafruit/Adafruit GFX Library
	bitbank2/AnimatedGIF@^2.1.0
	2dom/PxMatrix LED MATRIX library@^1.8.2
	toblum/TetrisAnimation@^1.1.0
	bodmer/TJpg_Decoder@^1.1.0
	me-no-dev/ESP Async WebServer@^1.2.3
	bblanchon/ArduinoJson@^7.0.4
	me-no-dev/ESPAsyncTCP@^1.2.2
	paulstoffregen/Time@^1.6.1
	lennarthennigs/Button2@^2.3.2
build_flags = -DCORE_DEBUG_LEVEL=3
